"""Deterministic checks on a downloaded PDF, run before any paid API call.

Every check here is cheap and certain. The expensive, uncertain step is the LLM,
and the point of this module is to keep obviously unusable files away from it —
a truncated download, an HTML error page served with a .pdf name, or a scanned
filing with no extractable text, which would otherwise produce a confident and
completely fabricated extraction.

Returns a status plus a human-readable reason rather than a bare bool, because
the reviewer needs to know WHY something was skipped.
"""
from __future__ import annotations

import io

VERIFIED = "verified"
REJECTED = "rejected"

PDF_MAGIC = b"%PDF-"
MIN_BYTES = 1_000
MAX_BYTES = 40 * 1024 * 1024
# Below this, the PDF is almost certainly scanned images. Extraction would still
# "succeed" and return invented numbers, so it is rejected rather than queued.
MIN_TEXT_CHARS = 400


def verify_pdf_bytes(data: bytes, *, min_text_chars: int = MIN_TEXT_CHARS) -> tuple[str, str]:
    """Return (status, detail). status is VERIFIED or REJECTED."""
    if not data:
        return REJECTED, "Empty response"
    if len(data) < MIN_BYTES:
        return REJECTED, f"Too small to be a filing ({len(data)} bytes)"
    if len(data) > MAX_BYTES:
        return REJECTED, f"Larger than the {MAX_BYTES // (1024 * 1024)}MB limit"
    if not data.lstrip()[:1024].startswith(PDF_MAGIC):
        head = data[:60].decode("utf-8", errors="replace").strip()
        return REJECTED, f"Not a PDF — no %PDF- header. Starts with: {head!r}"

    try:
        from pypdf import PdfReader
        reader = PdfReader(io.BytesIO(data))
        pages = len(reader.pages)
    except Exception as exc:
        return REJECTED, f"PDF could not be opened: {type(exc).__name__}: {exc}"

    if pages < 1:
        return REJECTED, "PDF reports zero pages"

    try:
        text = "\n\n".join((page.extract_text() or "") for page in reader.pages)
    except Exception as exc:
        return REJECTED, f"Text extraction failed: {type(exc).__name__}: {exc}"

    stripped = text.strip()
    if len(stripped) < min_text_chars:
        return REJECTED, (
            f"Only {len(stripped)} characters of extractable text across {pages} page(s) — "
            f"likely a scanned image. Extraction would invent figures, so it is not queued."
        )

    # Our own generated review reports carry already-normalised figures under
    # the source document's unit label; re-extracting one produces numbers that
    # disagree with their own unit. Covered by test_unit_scale.py.
    try:
        from app import _self_generated_report_warning
        if _self_generated_report_warning(text):
            return REJECTED, (
                "This is a review report generated by this tool, not an original filing"
            )
    except Exception:
        pass

    return VERIFIED, f"{pages} page(s), {len(stripped)} characters of extractable text"
